
name: Check

on:
  push:
    branches:
      - '**'

jobs:
  check:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Node dependencies
        run: npm ci

      - name: Format
        if: github.ref != 'refs/heads/main'
        run: npm run format

      - name: Setup Git remote
        run: ./scripts/setup-git-ci.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Check and Commit
        run: ./scripts/check-and-commit.sh
