name: Check

on:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  check:
    name: Check format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "npm"

      - name: Set up dependencies
        run: sudo ./scripts/setup.sh

      - name: Install Node dependencies
        run: npm ci

      - name: Check format
        run: npm run format-check

      - name: Check build
        run: npm run build
