# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish Site

on:
  workflow_dispatch:

jobs:
  build:
    name: Publish Site
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"

      - name: Install Node dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish website
        uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
        with:
          repo-token: ${{ secrets.GH_PAT }}
          site-directory: "build"
